 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/laravel-new-test:$COMMIT_SHA', '.']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/laravel-new-test:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'laravel-new-test'
   - '--image'
   - 'gcr.io/$PROJECT_ID/laravel-new-test:$COMMIT_SHA'
   - '--region'
   - 'europe-west3'
   - '--update-env-vars'
   - 'LARAVEL_INIT_ENABLED=1,LARAVEL_DB_MIGRATION_ENABLED=1,LARAVEL_DB_SEEDER_ENABLED=1'
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'services'
   - 'update'
   - 'laravel-new-test'
   - '--region'
   - 'europe-west3'
   - '--update-env-vars'
   - 'LARAVEL_DB_MIGRATION_ENABLED=0,LARAVEL_DB_SEEDER_ENABLED=0'
 images:
 - 'gcr.io/$PROJECT_ID/laravel-new-test:$COMMIT_SHA'
