steps:
  # running docker-compose
  - name: 'docker/compose:1.29.2'
    args: ['up', '-d']
  - name: 'composer'
    args: ['install']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'laravel-test-gcr:latest', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']

images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
