steps:
  # running docker-compose
#  - name: 'docker/compose:1.29.2'
#    args: ['up', '-d']
#  - name: 'composer'
#    args: ['install']
  - name: docker/compose
    args:
      - build
      - '--build-arg'
      - release_id=$SHORT_SHA
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - tag
      - 'laravel-test-gcr_php-fpm:latest'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    id: Tag
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud

images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
substitutions:
  _GCR_HOSTNAME: eu.gcr.io
  _SERVICE_NAME: laravel-new-test
