version: "3.1"

services:
    redis:
        image: redis:alpine
        container_name: app-redis

    webserver:
        image: nginx:alpine
        container_name: app-webserver
        working_dir: /
        volumes:
            - ./:/application
            - ./docker/nginx:/etc/nginx/conf.d
        ports:
            - "80:80"
        networks:
            testing_net:
                ipv4_address: 172.28.1.5

    php-fpm:
        build: docker/php-fpm
        container_name: app-php-fpm
        working_dir: /
        volumes:
            - ./:/application
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
        networks:
            testing_net:
                ipv4_address: 172.28.1.4

    composer:
        image: composer:latest
        container_name: app-composer
        working_dir: /application
        volumes:
            - ./:/application
        command: composer install --ignore-platform-reqs

networks:
    testing_net:
        ipam:
            driver: default
            config:
                -   subnet: 172.28.0.0/16
