version: "3.1"

services:
    web:
        build: .
        container_name: app-php-fpm8
        ports:
            - "80:80"
        volumes:
            - .:/var/www/rossmann

    postgres:
        image: postgres:9.5-alpine
        container_name: app-postgres
        volumes:
            - database:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgresdb
        ports:
            - "5432:5432"

    composer:
        image: composer:latest
        container_name: app-composer
        working_dir: /var/www/rossmann
        volumes:
            - ./:/var/www/rossmann
        command: composer install --ignore-platform-reqs

volumes:
    database:
